---
- block:
    - name: CentOS 7 upgrade all packages
      yum:
        name: "*"
        state: latest
      when: ansible_distribution_major_version == '7'

    - name: CentOS 8 upgrade all packages
      shell: dnf update -y --nobest
      register: result
      changed_when:
        - '"Nothing to do" not in result.stdout'
      when: ansible_distribution_major_version == '8'

    - name: CentOS grep upgrades
      shell: rpm -qa --last | grep "$(date +%a\ %d\ %b\ %Y)" |cut -f 1 -d " "
      register: result
      args:
        warn: no
      changed_when: false

    - name: CentOS show upgrades
      debug: msg="{{ result.stdout_lines }}"
  when: ansible_distribution == 'CentOS'


- block:
    - name: Debian & Ubuntu upgrade all packages
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: true
      register: result

    - name: Debian & Ubuntu grep upgrades
      shell: grep -E "^$(date +%Y-%m-%d).+ (install|upgrade) " /var/log/dpkg.log |cut -d " " -f 3-5
      register: result
      changed_when: false

    - name: Debian & Ubuntu show upgrades
      debug: msg="{{ result.stdout_lines }}"
  when: ansible_distribution in ['Debian', 'Ubuntu']
